/*
 * This file is part of Betaflight.
 *
 * Betaflight is free software. You can redistribute this software and/or
 * modify this software under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 */

#pragma once

#ifdef USE_MSP_GHOST_DP

#include "common/streambuf.h"
#include "msp/msp.h"

enum {
    MSP_DP_GHOST = 0x80,
    MSP_GHOST_DP_VERSION_1_0 = 0x10,
    MSP_GHOST_DP_HEADER_SIZE = 10,
    MSP_GHOST_DP_NEGOTIATION_PAYLOAD_MAX = 192,
};

typedef enum {
    MSP_GHOST_DP_ENDPOINT_UNSPECIFIED = 0,
    MSP_GHOST_DP_ENDPOINT_FLIGHT_CONTROLLER = 1,
    MSP_GHOST_DP_ENDPOINT_VRX = 2,
    MSP_GHOST_DP_ENDPOINT_CONFIGURATOR = 3,
    MSP_GHOST_DP_ENDPOINT_BROADCAST = 255,
} mspGhostDpEndpoint_e;

typedef enum {
    MSP_GHOST_DP_FLAG_REQUEST = 1 << 0,
    MSP_GHOST_DP_FLAG_RESPONSE = 1 << 1,
    MSP_GHOST_DP_FLAG_MORE = 1 << 2,
    MSP_GHOST_DP_FLAG_ERROR = 1 << 3,
    MSP_GHOST_DP_FLAG_VOLATILE = 1 << 4,
} mspGhostDpFlag_e;

typedef enum {
    MSP_GHOST_DP_SUBSCRIPTION_REQUIRED = 1 << 0,
    MSP_GHOST_DP_SUBSCRIPTION_OPTIONAL = 1 << 1,
    MSP_GHOST_DP_SUBSCRIPTION_HAS_DEADBAND = 1 << 2,
} mspGhostDpSubscriptionFlag_e;

typedef enum {
    MSP_GHOST_DP_HELLO_REQUEST = 0x01,
    MSP_GHOST_DP_HELLO_RESPONSE = 0x02,
    MSP_GHOST_DP_FIELD_CATALOG_REQUEST = 0x03,
    MSP_GHOST_DP_FIELD_CATALOG_RESPONSE = 0x04,
    MSP_GHOST_DP_SUBSCRIPTION_QUOTE = 0x10,
    MSP_GHOST_DP_SUBSCRIPTION_QUOTE_RESULT = 0x11,
    MSP_GHOST_DP_SUBSCRIPTION_COMMIT = 0x12,
    MSP_GHOST_DP_SUBSCRIPTION_RESULT = 0x13,
    MSP_GHOST_DP_SUBSCRIPTION_RENEW = 0x14,
    MSP_GHOST_DP_SUBSCRIPTION_RELEASE = 0x15,
    MSP_GHOST_DP_STREAM_MAP = 0x20,
    MSP_GHOST_DP_FIELD_DATA = 0x21,
    MSP_GHOST_DP_MISSION_INFO_REQUEST = 0x30,
    MSP_GHOST_DP_MISSION_INFO_RESPONSE = 0x31,
    MSP_GHOST_DP_MISSION_ITEM_REQUEST = 0x32,
    MSP_GHOST_DP_MISSION_ITEM_RESPONSE = 0x33,
} mspGhostDpMessageType_e;

typedef enum {
    MSP_GHOST_DP_STATUS_OK = 0,
    MSP_GHOST_DP_STATUS_BAD_LENGTH = 1,
    MSP_GHOST_DP_STATUS_UNSUPPORTED_VERSION = 2,
    MSP_GHOST_DP_STATUS_UNSUPPORTED_MESSAGE = 3,
    MSP_GHOST_DP_STATUS_INVALID_SESSION = 4,
    MSP_GHOST_DP_STATUS_INVALID_TRANSACTION = 5,
    MSP_GHOST_DP_STATUS_UNSUPPORTED_FIELD = 7,
    MSP_GHOST_DP_STATUS_INVALID_INSTANCE = 8,
    MSP_GHOST_DP_STATUS_INVALID_RATE = 10,
    MSP_GHOST_DP_STATUS_RATE_LIMITED = 11,
    MSP_GHOST_DP_STATUS_BANDWIDTH_EXCEEDED = 12,
    MSP_GHOST_DP_STATUS_TOO_MANY_FIELDS = 13,
    MSP_GHOST_DP_STATUS_BUSY = 19,
    MSP_GHOST_DP_STATUS_INVALID_MISSION = 22,
} mspGhostDpStatus_e;

typedef enum {
    MSP_GHOST_DP_VALUE_U8 = 1,
    MSP_GHOST_DP_VALUE_I8 = 2,
    MSP_GHOST_DP_VALUE_U16 = 3,
    MSP_GHOST_DP_VALUE_I16 = 4,
    MSP_GHOST_DP_VALUE_U32 = 5,
    MSP_GHOST_DP_VALUE_I32 = 6,
    MSP_GHOST_DP_VALUE_U64 = 7,
    MSP_GHOST_DP_VALUE_I64 = 8,
    MSP_GHOST_DP_VALUE_F32 = 9,
    MSP_GHOST_DP_VALUE_F64 = 10,
    MSP_GHOST_DP_VALUE_BOOL = 11,
    MSP_GHOST_DP_VALUE_UTF8 = 12,
    MSP_GHOST_DP_VALUE_BYTES = 13,
} mspGhostDpValueType_e;

typedef enum {
    MSP_GHOST_DP_UNIT_NONE = 0,
    MSP_GHOST_DP_UNIT_DEGREE = 1,
    MSP_GHOST_DP_UNIT_METRE = 2,
    MSP_GHOST_DP_UNIT_METRES_PER_SECOND = 3,
    MSP_GHOST_DP_UNIT_VOLT = 4,
    MSP_GHOST_DP_UNIT_AMPERE = 5,
    MSP_GHOST_DP_UNIT_AMPERE_HOUR = 6,
    MSP_GHOST_DP_UNIT_SECOND = 7,
    MSP_GHOST_DP_UNIT_PERCENT = 8,
    MSP_GHOST_DP_UNIT_HERTZ = 9,
    MSP_GHOST_DP_UNIT_COUNT = 10,
    MSP_GHOST_DP_UNIT_DEGREES_PER_SECOND = 11,
    MSP_GHOST_DP_UNIT_WATT_HOUR = 12,
} mspGhostDpUnit_e;

typedef enum {
    MSP_GHOST_DP_FIELD_INSTANCE_AWARE = 1 << 0,
    MSP_GHOST_DP_FIELD_PRIMARY_SUPPORTED = 1 << 1,
    MSP_GHOST_DP_FIELD_TEMPORARILY_INVALID = 1 << 2,
    MSP_GHOST_DP_FIELD_SIGNED = 1 << 3,
    MSP_GHOST_DP_FIELD_VARIABLE_LENGTH = 1 << 4,
} mspGhostDpFieldFlag_e;

mspResult_e mspGhostDpProcessCommand(sbuf_t *src, sbuf_t *dst);
void mspGhostDpProcess(void);

#endif // USE_MSP_GHOST_DP
